"""Regenerates src/Core/Display/ArtTextureData.lua from the community listfile.

One family is taken: Textures/SpellActivationOverlays/*.blp, the art the game itself flashes
around the screen when a proc lands. It is hand-made, it reads at a glance, and it is the look
this feature exists to offer.

The rest of the client's effect library is not offered. SPELLS/ holds thousands of tiling
surfaces, masks and gradients that look like nothing hung beside a unit, and no keyword filter
separates the few good ones from the rest, so the shapes beyond these come from the addon's own
art instead (scripts/GenerateShapeTextures.py).

Rows carry the file id and the path. The id is what draws, because ids never change. The path is
what the client is asked about at load, so a file this build does not have is dropped rather than
offered as an empty square.

Usage (from the repo root):

    python scripts/GenerateArtTextures.py

Pass --cache DIR to reuse already-downloaded listfile parts.
"""

import argparse
import os
import re
import sys
import urllib.request

LISTFILE_ROOT = "https://raw.githubusercontent.com/wowdev/wow-listfile/master/parts/"
PARTS = ("misc.csv",)
OUTPUT = os.path.join("src", "Core", "Display", "ArtTextureData.lua")

ALERT_DIR = "textures/spellactivationoverlays/"
# Which of the 80-odd overlays are worth offering, picked by eye. The rest are class-specific
# doodles that read as a smudge once they are off the spell they were drawn for. A name ending in
# * takes its numbered and recoloured variants with it.
ALERT_KEEP = (
    "Backlash*",
    "Blood Surge",
    "Brain Freeze",
    "Daybreak",
    "Frozen Fingers",
    "Fulmination",
    "Fury Of Stormrage",
    "Hand Of Light",
    "Maelstrom*",
    "Predatory Swiftness*",
    "Rime",
    "Serendipity",
    "Shadow Of Death",
    "Shooting Stars",
    "Tooth And Claw",
)


def fetch(part, cache):
    path = os.path.join(cache, part)

    if not os.path.exists(path):
        os.makedirs(cache, exist_ok=True)
        urllib.request.urlretrieve(LISTFILE_ROOT + part, path)

    with open(path, encoding="utf-8", errors="replace") as handle:
        for line in handle:
            file_id, _, file_path = line.strip().partition(";")

            if file_id.isdigit() and file_path:
                yield int(file_id), file_path


def label_for(file_path):
    """The file name, tidied into something worth reading in a list."""
    name = re.sub(r"\.\w+$", "", file_path.rsplit("/", 1)[-1])
    # Art added in a given expansion is prefixed with its number, which says nothing about how
    # the texture looks and sorts every one of them under the digit.
    name = re.sub(r"^\d+fx[_\- ]*", "", name, flags=re.IGNORECASE)
    name = re.sub(r"[_\-]+", " ", name).strip()
    words = [word[:1].upper() + word[1:].lower() for word in name.split()]

    return " ".join(words)


def collect(rows):
    alerts = {}

    for file_id, file_path in rows:
        lower = file_path.lower()

        if lower.endswith(".blp") and lower.startswith(ALERT_DIR):
            alerts[file_id] = file_path

    return alerts


def wanted(label):
    for pattern in ALERT_KEEP:
        if pattern.endswith("*"):
            if label.lower().startswith(pattern[:-1].lower()):
                return True
        elif label.lower() == pattern.lower():
            return True

    return False


def unique_by_label(entries):
    """One row per look. The listfile carries the same art under several spellings, and a list
    with four rows called "Aura Rune 8" in it is a list nobody can pick from."""
    seen, out = set(), []

    for file_id, file_path in sorted(entries.items()):
        label = label_for(file_path)
        key = label.lower()

        if key in seen or not wanted(label):
            continue

        seen.add(key)
        out.append((file_id, label, file_path))

    out.sort(key=lambda row: row[1].lower())

    return out


def write(alerts, output):
    lines = [
        "---@type string, Addon",
        "local _, addon = ...",
        "",
        "-- GENERATED by scripts/GenerateArtTextures.py from the community listfile. Do not edit by",
        "-- hand: re-run the script instead.",
        "--",
        "-- Every row is { file id, label, path }. The id is what draws, because ids outlive the paths",
        "-- that name them. The path is what the client is asked about at load, so art a build never",
        "-- shipped is dropped rather than offered as an empty square.",
        "",
        "---@class ArtTextureData",
        "local M = {}",
        "",
        "addon.Core.ArtTextureData = M",
        "",
    ]

    lines.append("-- The art the game flashes around the screen when a proc lands.")
    lines.append("M.Alerts = {")

    for file_id, label, file_path in alerts:
        lines.append('\t{ %d, "%s", [[%s]] },' % (file_id, label.replace('"', '\\"'), file_path))

    lines.append("}")
    lines.append("")

    lines.append("---@class ArtTextureData")
    lines.append("---@field Alerts table[]")
    lines.append("")

    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", default=os.path.join("scripts", ".listfile"),
                        help="where downloaded listfile parts are kept")
    parser.add_argument("--output", default=OUTPUT)
    args = parser.parse_args()

    rows = []

    for part in PARTS:
        rows.extend(fetch(part, args.cache))

    alerts = unique_by_label(collect(rows))

    write(alerts, args.output)

    print("%d alert textures -> %s" % (len(alerts), args.output))

    return 0


if __name__ == "__main__":
    sys.exit(main())
